fix: revert min unity version change
This updates the min version back temporarily so the GitHub workflow pushes the dynamic asset changes downstream. This was logged when we merged:
```
error: patch failed: package/package.json:3
error: package/package.json: patch does not apply
```

It seems like changing this and the version number complicated the package.json diff-ing, so I'll update the min unity version in a different PR later.

Diffs=
1354f137ae fix: revert unity version change (#8432)
d74aec2140 feat: unity dynamic asset loading (#8378)

Co-authored-by: Adam <67035612+damzobridge@users.noreply.github.com>